### PR TITLE
Test against different Symfony + PHP versions (step 1 to support Symfony 3)

### PR DESCRIPTION
**Pull request by wouterj**
This bundle doesn't support Symfony 3, although the composer.json version constraint claims it does.

### CODE REVIEW

**Comment by bobvandevijver** [comment]
Could you elaborate on why we are not supporting Symfony 3.x, so that we can look into that?

**Comment by wouterj** [comment]
@bobvandevijver I've now changed this PR to improve your Composer and Travis config. This means that this bundle is now tested against different versions of Symfony (2.3, 2.7, 2.8 and 3.0) and different PHP versions (5.3, 5.4, 5.5, 5.6, 7.0 and hhvm).

If you open the 2.8 tests, you'll probably see a list of deprecation notices. All these notices should be fixed in order to support Symfony 3. From what I saw in a quick search through this bundle, the Form type name refactoring (names are removed in 3.0, the FQCN of the FormType is used instead) will be one of the major refactorings for this bundle to support Symfony 3.

I don't have much experience with this bundle, so feel free to take over my PR and fix all notices.

**Comment by wouterj** [comment]
Seems like the generated code, containing the deprecated features, aren't tested.

The remaining deprecation notices will be fixed by https://github.com/cedriclombardot/TwigGenerator/pull/21

**Comment by bobvandevijver** [comment]
@WouterJ I did not notice this earlier, but this is the old-legacy bundle. For the new-unstable bundle there is a full PR waiting to be merged with Symfony 2.8 & 3.0 supoort, so you should move to that one (see https://github.com/symfony2admingenerator/GeneratorBundle/pull/224).

**Pull request closed without merging**
