### PR TITLE
Issue 806 fix (Doctrine ORM Manager named "default" does not exist)

### PR DESCRIPTION
**Pull request by crash21**
Issue 806 fix (Doctrine ORM Manager named "default" does not exist)

### CODE REVIEW

**Comment by crash21** [comment]
Hey, why this not merged yet?

**Comment by loostro** [comment]
@crash21 christmas, new year... it was overlooked :) sorry to keep you waiting, merged - thanks!

**Comment by crash21** [comment]
hehe np :D thanks!

**Comment by loostro** [comment]
also merged into 1.1 and master branches

**Pull request merged**
